In \[1\]:

    import pandas as pd
    import numpy as np
    import matplotlib.pyplot as plt
    from sklearn.model_selection import train_test_split

In \[3\]:

    df=pd.read_csv("/home/divum/ML/DATASETS/WA_Fn-UseC_-Telco-Customer-Churn.csv")
    df.head()

Out\[3\]:

|     | customerID | gender | SeniorCitizen | Partner | Dependents | tenure | PhoneService | MultipleLines    | InternetService | OnlineSecurity | ... | DeviceProtection | TechSupport | StreamingTV | StreamingMovies | Contract       | PaperlessBilling | PaymentMethod             | MonthlyCharges | TotalCharges | Churn |
|-----|------------|--------|---------------|---------|------------|--------|--------------|------------------|-----------------|----------------|-----|------------------|-------------|-------------|-----------------|----------------|------------------|---------------------------|----------------|--------------|-------|
| 0   | 7590-VHVEG | Female | 0             | Yes     | No         | 1      | No           | No phone service | DSL             | No             | ... | No               | No          | No          | No              | Month-to-month | Yes              | Electronic check          | 29.85          | 29.85        | No    |
| 1   | 5575-GNVDE | Male   | 0             | No      | No         | 34     | Yes          | No               | DSL             | Yes            | ... | Yes              | No          | No          | No              | One year       | No               | Mailed check              | 56.95          | 1889.5       | No    |
| 2   | 3668-QPYBK | Male   | 0             | No      | No         | 2      | Yes          | No               | DSL             | Yes            | ... | No               | No          | No          | No              | Month-to-month | Yes              | Mailed check              | 53.85          | 108.15       | Yes   |
| 3   | 7795-CFOCW | Male   | 0             | No      | No         | 45     | No           | No phone service | DSL             | Yes            | ... | Yes              | Yes         | No          | No              | One year       | No               | Bank transfer (automatic) | 42.30          | 1840.75      | No    |
| 4   | 9237-HQITU | Female | 0             | No      | No         | 2      | Yes          | No               | Fiber optic     | No             | ... | No               | No          | No          | No              | Month-to-month | Yes              | Electronic check          | 70.70          | 151.65       | Yes   |

5 rows × 21 columns

In \[4\]:

    df.drop('customerID',axis='columns',inplace=True)

In \[5\]:

    df

Out\[5\]:

|      | gender | SeniorCitizen | Partner | Dependents | tenure | PhoneService | MultipleLines    | InternetService | OnlineSecurity | OnlineBackup | DeviceProtection | TechSupport | StreamingTV | StreamingMovies | Contract       | PaperlessBilling | PaymentMethod             | MonthlyCharges | TotalCharges | Churn |
|------|--------|---------------|---------|------------|--------|--------------|------------------|-----------------|----------------|--------------|------------------|-------------|-------------|-----------------|----------------|------------------|---------------------------|----------------|--------------|-------|
| 0    | Female | 0             | Yes     | No         | 1      | No           | No phone service | DSL             | No             | Yes          | No               | No          | No          | No              | Month-to-month | Yes              | Electronic check          | 29.85          | 29.85        | No    |
| 1    | Male   | 0             | No      | No         | 34     | Yes          | No               | DSL             | Yes            | No           | Yes              | No          | No          | No              | One year       | No               | Mailed check              | 56.95          | 1889.5       | No    |
| 2    | Male   | 0             | No      | No         | 2      | Yes          | No               | DSL             | Yes            | Yes          | No               | No          | No          | No              | Month-to-month | Yes              | Mailed check              | 53.85          | 108.15       | Yes   |
| 3    | Male   | 0             | No      | No         | 45     | No           | No phone service | DSL             | Yes            | No           | Yes              | Yes         | No          | No              | One year       | No               | Bank transfer (automatic) | 42.30          | 1840.75      | No    |
| 4    | Female | 0             | No      | No         | 2      | Yes          | No               | Fiber optic     | No             | No           | No               | No          | No          | No              | Month-to-month | Yes              | Electronic check          | 70.70          | 151.65       | Yes   |
| ...  | ...    | ...           | ...     | ...        | ...    | ...          | ...              | ...             | ...            | ...          | ...              | ...         | ...         | ...             | ...            | ...              | ...                       | ...            | ...          | ...   |
| 7038 | Male   | 0             | Yes     | Yes        | 24     | Yes          | Yes              | DSL             | Yes            | No           | Yes              | Yes         | Yes         | Yes             | One year       | Yes              | Mailed check              | 84.80          | 1990.5       | No    |
| 7039 | Female | 0             | Yes     | Yes        | 72     | Yes          | Yes              | Fiber optic     | No             | Yes          | Yes              | No          | Yes         | Yes             | One year       | Yes              | Credit card (automatic)   | 103.20         | 7362.9       | No    |
| 7040 | Female | 0             | Yes     | Yes        | 11     | No           | No phone service | DSL             | Yes            | No           | No               | No          | No          | No              | Month-to-month | Yes              | Electronic check          | 29.60          | 346.45       | No    |
| 7041 | Male   | 1             | Yes     | No         | 4      | Yes          | Yes              | Fiber optic     | No             | No           | No               | No          | No          | No              | Month-to-month | Yes              | Mailed check              | 74.40          | 306.6        | Yes   |
| 7042 | Male   | 0             | No      | No         | 66     | Yes          | No               | Fiber optic     | Yes            | No           | Yes              | Yes         | Yes         | Yes             | Two year       | Yes              | Bank transfer (automatic) | 105.65         | 6844.5       | No    |

7043 rows × 20 columns

In \[6\]:

    df.dtypes

Out\[6\]:

    gender               object
    SeniorCitizen         int64
    Partner              object
    Dependents           object
    tenure                int64
    PhoneService         object
    MultipleLines        object
    InternetService      object
    OnlineSecurity       object
    OnlineBackup         object
    DeviceProtection     object
    TechSupport          object
    StreamingTV          object
    StreamingMovies      object
    Contract             object
    PaperlessBilling     object
    PaymentMethod        object
    MonthlyCharges      float64
    TotalCharges         object
    Churn                object
    dtype: object

In \[7\]:

    df.TotalCharges.values

Out\[7\]:

    array(['29.85', '1889.5', '108.15', ..., '346.45', '306.6', '6844.5'],
          dtype=object)

In \[10\]:

    pd.to_numeric(df.TotalCharges,errors='coerce').isnull().sum()

Out\[10\]:

    11

In \[11\]:

    df.iloc[488].TotalCharges

Out\[11\]:

    ' '

In \[13\]:

    df1=df[df.TotalCharges!=' ']

In \[14\]:

    df1

Out\[14\]:

|      | gender | SeniorCitizen | Partner | Dependents | tenure | PhoneService | MultipleLines    | InternetService | OnlineSecurity | OnlineBackup | DeviceProtection | TechSupport | StreamingTV | StreamingMovies | Contract       | PaperlessBilling | PaymentMethod             | MonthlyCharges | TotalCharges | Churn |
|------|--------|---------------|---------|------------|--------|--------------|------------------|-----------------|----------------|--------------|------------------|-------------|-------------|-----------------|----------------|------------------|---------------------------|----------------|--------------|-------|
| 0    | Female | 0             | Yes     | No         | 1      | No           | No phone service | DSL             | No             | Yes          | No               | No          | No          | No              | Month-to-month | Yes              | Electronic check          | 29.85          | 29.85        | No    |
| 1    | Male   | 0             | No      | No         | 34     | Yes          | No               | DSL             | Yes            | No           | Yes              | No          | No          | No              | One year       | No               | Mailed check              | 56.95          | 1889.5       | No    |
| 2    | Male   | 0             | No      | No         | 2      | Yes          | No               | DSL             | Yes            | Yes          | No               | No          | No          | No              | Month-to-month | Yes              | Mailed check              | 53.85          | 108.15       | Yes   |
| 3    | Male   | 0             | No      | No         | 45     | No           | No phone service | DSL             | Yes            | No           | Yes              | Yes         | No          | No              | One year       | No               | Bank transfer (automatic) | 42.30          | 1840.75      | No    |
| 4    | Female | 0             | No      | No         | 2      | Yes          | No               | Fiber optic     | No             | No           | No               | No          | No          | No              | Month-to-month | Yes              | Electronic check          | 70.70          | 151.65       | Yes   |
| ...  | ...    | ...           | ...     | ...        | ...    | ...          | ...              | ...             | ...            | ...          | ...              | ...         | ...         | ...             | ...            | ...              | ...                       | ...            | ...          | ...   |
| 7038 | Male   | 0             | Yes     | Yes        | 24     | Yes          | Yes              | DSL             | Yes            | No           | Yes              | Yes         | Yes         | Yes             | One year       | Yes              | Mailed check              | 84.80          | 1990.5       | No    |
| 7039 | Female | 0             | Yes     | Yes        | 72     | Yes          | Yes              | Fiber optic     | No             | Yes          | Yes              | No          | Yes         | Yes             | One year       | Yes              | Credit card (automatic)   | 103.20         | 7362.9       | No    |
| 7040 | Female | 0             | Yes     | Yes        | 11     | No           | No phone service | DSL             | Yes            | No           | No               | No          | No          | No              | Month-to-month | Yes              | Electronic check          | 29.60          | 346.45       | No    |
| 7041 | Male   | 1             | Yes     | No         | 4      | Yes          | Yes              | Fiber optic     | No             | No           | No               | No          | No          | No              | Month-to-month | Yes              | Mailed check              | 74.40          | 306.6        | Yes   |
| 7042 | Male   | 0             | No      | No         | 66     | Yes          | No               | Fiber optic     | Yes            | No           | Yes              | Yes         | Yes         | Yes             | Two year       | Yes              | Bank transfer (automatic) | 105.65         | 6844.5       | No    |

7032 rows × 20 columns

In \[15\]:

    df1.dtypes

Out\[15\]:

    gender               object
    SeniorCitizen         int64
    Partner              object
    Dependents           object
    tenure                int64
    PhoneService         object
    MultipleLines        object
    InternetService      object
    OnlineSecurity       object
    OnlineBackup         object
    DeviceProtection     object
    TechSupport          object
    StreamingTV          object
    StreamingMovies      object
    Contract             object
    PaperlessBilling     object
    PaymentMethod        object
    MonthlyCharges      float64
    TotalCharges         object
    Churn                object
    dtype: object

In \[16\]:

    df1.TotalCharges=pd.to_numeric(df1.TotalCharges)

    /tmp/ipykernel_48466/695980592.py:1: SettingWithCopyWarning: 
    A value is trying to be set on a copy of a slice from a DataFrame.
    Try using .loc[row_indexer,col_indexer] = value instead

    See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
      df1.TotalCharges=pd.to_numeric(df1.TotalCharges)

In \[17\]:

    df1.dtypes

Out\[17\]:

    gender               object
    SeniorCitizen         int64
    Partner              object
    Dependents           object
    tenure                int64
    PhoneService         object
    MultipleLines        object
    InternetService      object
    OnlineSecurity       object
    OnlineBackup         object
    DeviceProtection     object
    TechSupport          object
    StreamingTV          object
    StreamingMovies      object
    Contract             object
    PaperlessBilling     object
    PaymentMethod        object
    MonthlyCharges      float64
    TotalCharges        float64
    Churn                object
    dtype: object

In \[18\]:

    def print_unique_col_values(df):
           for column in df:
                if df[column].dtypes=='object':
                    print(f'{column}: {df[column].unique()}') 

In \[19\]:

    print_unique_col_values(df1)

    gender: ['Female' 'Male']
    Partner: ['Yes' 'No']
    Dependents: ['No' 'Yes']
    PhoneService: ['No' 'Yes']
    MultipleLines: ['No phone service' 'No' 'Yes']
    InternetService: ['DSL' 'Fiber optic' 'No']
    OnlineSecurity: ['No' 'Yes' 'No internet service']
    OnlineBackup: ['Yes' 'No' 'No internet service']
    DeviceProtection: ['No' 'Yes' 'No internet service']
    TechSupport: ['No' 'Yes' 'No internet service']
    StreamingTV: ['No' 'Yes' 'No internet service']
    StreamingMovies: ['No' 'Yes' 'No internet service']
    Contract: ['Month-to-month' 'One year' 'Two year']
    PaperlessBilling: ['Yes' 'No']
    PaymentMethod: ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
     'Credit card (automatic)']
    Churn: ['No' 'Yes']

In \[20\]:

    df1.replace('No internet service','No',inplace=True)
    df1.replace('No phone service','No',inplace=True)

    /tmp/ipykernel_48466/2045096646.py:1: SettingWithCopyWarning: 
    A value is trying to be set on a copy of a slice from a DataFrame

    See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
      df1.replace('No internet service','No',inplace=True)
    /tmp/ipykernel_48466/2045096646.py:2: SettingWithCopyWarning: 
    A value is trying to be set on a copy of a slice from a DataFrame

    See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
      df1.replace('No phone service','No',inplace=True)

In \[21\]:

    print_unique_col_values(df1)

    gender: ['Female' 'Male']
    Partner: ['Yes' 'No']
    Dependents: ['No' 'Yes']
    PhoneService: ['No' 'Yes']
    MultipleLines: ['No' 'Yes']
    InternetService: ['DSL' 'Fiber optic' 'No']
    OnlineSecurity: ['No' 'Yes']
    OnlineBackup: ['Yes' 'No']
    DeviceProtection: ['No' 'Yes']
    TechSupport: ['No' 'Yes']
    StreamingTV: ['No' 'Yes']
    StreamingMovies: ['No' 'Yes']
    Contract: ['Month-to-month' 'One year' 'Two year']
    PaperlessBilling: ['Yes' 'No']
    PaymentMethod: ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
     'Credit card (automatic)']
    Churn: ['No' 'Yes']

In \[22\]:

    yes_no_columns = ['Partner','Dependents','PhoneService','MultipleLines','OnlineSecurity','OnlineBackup',
                      'DeviceProtection','TechSupport','StreamingTV','StreamingMovies','PaperlessBilling','Churn']
    for col in yes_no_columns:
        df1[col].replace({'Yes': 1,'No': 0},inplace=True)

    /tmp/ipykernel_48466/1648037665.py:4: SettingWithCopyWarning: 
    A value is trying to be set on a copy of a slice from a DataFrame

    See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
      df1[col].replace({'Yes': 1,'No': 0},inplace=True)

In \[23\]:

    for col in df1:
        print(f'{col}: {df1[col].unique()}') 

    gender: ['Female' 'Male']
    SeniorCitizen: [0 1]
    Partner: [1 0]
    Dependents: [0 1]
    tenure: [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
      5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
     32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26 39]
    PhoneService: [0 1]
    MultipleLines: [0 1]
    InternetService: ['DSL' 'Fiber optic' 'No']
    OnlineSecurity: [0 1]
    OnlineBackup: [1 0]
    DeviceProtection: [0 1]
    TechSupport: [0 1]
    StreamingTV: [0 1]
    StreamingMovies: [0 1]
    Contract: ['Month-to-month' 'One year' 'Two year']
    PaperlessBilling: [1 0]
    PaymentMethod: ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
     'Credit card (automatic)']
    MonthlyCharges: [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
    TotalCharges: [  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]
    Churn: [0 1]

In \[24\]:

    df1['gender'].replace({'Female':1,'Male':0},inplace=True)

    /tmp/ipykernel_48466/698335744.py:1: SettingWithCopyWarning: 
    A value is trying to be set on a copy of a slice from a DataFrame

    See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
      df1['gender'].replace({'Female':1,'Male':0},inplace=True)

In \[25\]:

    df1.gender.unique()

Out\[25\]:

    array([1, 0])

In \[26\]:

    df1.dtypes

Out\[26\]:

    gender                int64
    SeniorCitizen         int64
    Partner               int64
    Dependents            int64
    tenure                int64
    PhoneService          int64
    MultipleLines         int64
    InternetService      object
    OnlineSecurity        int64
    OnlineBackup          int64
    DeviceProtection      int64
    TechSupport           int64
    StreamingTV           int64
    StreamingMovies       int64
    Contract             object
    PaperlessBilling      int64
    PaymentMethod        object
    MonthlyCharges      float64
    TotalCharges        float64
    Churn                 int64
    dtype: object

In \[27\]:

    df2 = pd.get_dummies(data=df1, columns=['InternetService','Contract','PaymentMethod'])
    df2.columns

Out\[27\]:

    Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
           'PhoneService', 'MultipleLines', 'OnlineSecurity', 'OnlineBackup',
           'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
           'PaperlessBilling', 'MonthlyCharges', 'TotalCharges', 'Churn',
           'InternetService_DSL', 'InternetService_Fiber optic',
           'InternetService_No', 'Contract_Month-to-month', 'Contract_One year',
           'Contract_Two year', 'PaymentMethod_Bank transfer (automatic)',
           'PaymentMethod_Credit card (automatic)',
           'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
          dtype='object')

In \[28\]:

    df2.dtypes

Out\[28\]:

    gender                                       int64
    SeniorCitizen                                int64
    Partner                                      int64
    Dependents                                   int64
    tenure                                       int64
    PhoneService                                 int64
    MultipleLines                                int64
    OnlineSecurity                               int64
    OnlineBackup                                 int64
    DeviceProtection                             int64
    TechSupport                                  int64
    StreamingTV                                  int64
    StreamingMovies                              int64
    PaperlessBilling                             int64
    MonthlyCharges                             float64
    TotalCharges                               float64
    Churn                                        int64
    InternetService_DSL                          uint8
    InternetService_Fiber optic                  uint8
    InternetService_No                           uint8
    Contract_Month-to-month                      uint8
    Contract_One year                            uint8
    Contract_Two year                            uint8
    PaymentMethod_Bank transfer (automatic)      uint8
    PaymentMethod_Credit card (automatic)        uint8
    PaymentMethod_Electronic check               uint8
    PaymentMethod_Mailed check                   uint8
    dtype: object

In \[29\]:

    cols_to_scale = ['tenure','MonthlyCharges','TotalCharges']

    from sklearn.preprocessing import MinMaxScaler
    scaler = MinMaxScaler()
    df2[cols_to_scale] = scaler.fit_transform(df2[cols_to_scale])

In \[30\]:

    for col in df2:
        print(f'{col}: {df2[col].unique()}')

    gender: [1 0]
    SeniorCitizen: [0 1]
    Partner: [1 0]
    Dependents: [0 1]
    tenure: [0.         0.46478873 0.01408451 0.61971831 0.09859155 0.29577465
     0.12676056 0.38028169 0.85915493 0.16901408 0.21126761 0.8028169
     0.67605634 0.33802817 0.95774648 0.71830986 0.98591549 0.28169014
     0.15492958 0.4084507  0.64788732 1.         0.22535211 0.36619718
     0.05633803 0.63380282 0.14084507 0.97183099 0.87323944 0.5915493
     0.1971831  0.83098592 0.23943662 0.91549296 0.11267606 0.02816901
     0.42253521 0.69014085 0.88732394 0.77464789 0.08450704 0.57746479
     0.47887324 0.66197183 0.3943662  0.90140845 0.52112676 0.94366197
     0.43661972 0.76056338 0.50704225 0.49295775 0.56338028 0.07042254
     0.04225352 0.45070423 0.92957746 0.30985915 0.78873239 0.84507042
     0.18309859 0.26760563 0.73239437 0.54929577 0.81690141 0.32394366
     0.6056338  0.25352113 0.74647887 0.70422535 0.35211268 0.53521127]
    PhoneService: [0 1]
    MultipleLines: [0 1]
    OnlineSecurity: [0 1]
    OnlineBackup: [1 0]
    DeviceProtection: [0 1]
    TechSupport: [0 1]
    StreamingTV: [0 1]
    StreamingMovies: [0 1]
    PaperlessBilling: [1 0]
    MonthlyCharges: [0.11542289 0.38507463 0.35422886 ... 0.44626866 0.25820896 0.60149254]
    TotalCharges: [0.0012751  0.21586661 0.01031041 ... 0.03780868 0.03321025 0.78764136]
    Churn: [0 1]
    InternetService_DSL: [1 0]
    InternetService_Fiber optic: [0 1]
    InternetService_No: [0 1]
    Contract_Month-to-month: [1 0]
    Contract_One year: [0 1]
    Contract_Two year: [0 1]
    PaymentMethod_Bank transfer (automatic): [0 1]
    PaymentMethod_Credit card (automatic): [0 1]
    PaymentMethod_Electronic check: [1 0]
    PaymentMethod_Mailed check: [0 1]

In \[33\]:

    x = df2.drop('Churn',axis='columns')
    y = df2['Churn']

In \[34\]:

    xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=7)

In \[40\]:

    import tensorflow as tf
    from tensorflow import keras

    model=keras.Sequential([
        keras.layers.Dense(26,input_shape=(26,),activation='relu'),
        keras.layers.Dense(16,activation='relu'),
        keras.layers.Dense(1,activation='sigmoid')
    ])

    model.compile(optimizer='adam',
                 loss='binary_crossentropy',
                 metrics=['accuracy'])
    model.fit(xtrain,ytrain,epochs=100)

    Epoch 1/100
    176/176 [==============================] - 0s 923us/step - loss: 0.4910 - accuracy: 0.7477
    Epoch 2/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.4352 - accuracy: 0.7906
    Epoch 3/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.4255 - accuracy: 0.7993
    Epoch 4/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.4196 - accuracy: 0.8023
    Epoch 5/100
    176/176 [==============================] - 0s 931us/step - loss: 0.4171 - accuracy: 0.8060
    Epoch 6/100
    176/176 [==============================] - 0s 990us/step - loss: 0.4150 - accuracy: 0.8050
    Epoch 7/100
    176/176 [==============================] - 0s 944us/step - loss: 0.4148 - accuracy: 0.8039
    Epoch 8/100
    176/176 [==============================] - 0s 946us/step - loss: 0.4119 - accuracy: 0.8096
    Epoch 9/100
    176/176 [==============================] - 0s 940us/step - loss: 0.4102 - accuracy: 0.8087
    Epoch 10/100
    176/176 [==============================] - 0s 976us/step - loss: 0.4096 - accuracy: 0.8082
    Epoch 11/100
    176/176 [==============================] - 0s 985us/step - loss: 0.4083 - accuracy: 0.8092
    Epoch 12/100
    176/176 [==============================] - 0s 925us/step - loss: 0.4065 - accuracy: 0.8100
    Epoch 13/100
    176/176 [==============================] - 0s 935us/step - loss: 0.4064 - accuracy: 0.8107
    Epoch 14/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.4050 - accuracy: 0.8108
    Epoch 15/100
    176/176 [==============================] - 0s 966us/step - loss: 0.4039 - accuracy: 0.8114
    Epoch 16/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.4033 - accuracy: 0.8108
    Epoch 17/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.4013 - accuracy: 0.8116
    Epoch 18/100
    176/176 [==============================] - 0s 946us/step - loss: 0.4012 - accuracy: 0.8128
    Epoch 19/100
    176/176 [==============================] - 0s 999us/step - loss: 0.4007 - accuracy: 0.8098
    Epoch 20/100
    176/176 [==============================] - 0s 972us/step - loss: 0.3991 - accuracy: 0.8124
    Epoch 21/100
    176/176 [==============================] - 0s 946us/step - loss: 0.3986 - accuracy: 0.8119
    Epoch 22/100
    176/176 [==============================] - 0s 919us/step - loss: 0.3960 - accuracy: 0.8146
    Epoch 23/100
    176/176 [==============================] - 0s 921us/step - loss: 0.3965 - accuracy: 0.8123
    Epoch 24/100
    176/176 [==============================] - 0s 919us/step - loss: 0.3959 - accuracy: 0.8124
    Epoch 25/100
    176/176 [==============================] - 0s 959us/step - loss: 0.3951 - accuracy: 0.8114
    Epoch 26/100
    176/176 [==============================] - 0s 984us/step - loss: 0.3929 - accuracy: 0.8153
    Epoch 27/100
    176/176 [==============================] - 0s 988us/step - loss: 0.3927 - accuracy: 0.8162
    Epoch 28/100
    176/176 [==============================] - 0s 909us/step - loss: 0.3929 - accuracy: 0.8151
    Epoch 29/100
    176/176 [==============================] - 0s 897us/step - loss: 0.3906 - accuracy: 0.8171
    Epoch 30/100
    176/176 [==============================] - 0s 954us/step - loss: 0.3907 - accuracy: 0.8132
    Epoch 31/100
    176/176 [==============================] - 0s 935us/step - loss: 0.3894 - accuracy: 0.8158
    Epoch 32/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3896 - accuracy: 0.8169
    Epoch 33/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3887 - accuracy: 0.8160
    Epoch 34/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3869 - accuracy: 0.8149
    Epoch 35/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3872 - accuracy: 0.8156
    Epoch 36/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3858 - accuracy: 0.8171
    Epoch 37/100
    176/176 [==============================] - 0s 953us/step - loss: 0.3847 - accuracy: 0.8169
    Epoch 38/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3843 - accuracy: 0.8146
    Epoch 39/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3839 - accuracy: 0.8164
    Epoch 40/100
    176/176 [==============================] - 0s 962us/step - loss: 0.3825 - accuracy: 0.8153
    Epoch 41/100
    176/176 [==============================] - 0s 991us/step - loss: 0.3824 - accuracy: 0.8178
    Epoch 42/100
    176/176 [==============================] - 0s 948us/step - loss: 0.3827 - accuracy: 0.8178
    Epoch 43/100
    176/176 [==============================] - 0s 944us/step - loss: 0.3804 - accuracy: 0.8172
    Epoch 44/100
    176/176 [==============================] - 0s 938us/step - loss: 0.3806 - accuracy: 0.8174
    Epoch 45/100
    176/176 [==============================] - 0s 951us/step - loss: 0.3794 - accuracy: 0.8149
    Epoch 46/100
    176/176 [==============================] - 0s 958us/step - loss: 0.3784 - accuracy: 0.8233
    Epoch 47/100
    176/176 [==============================] - 0s 949us/step - loss: 0.3793 - accuracy: 0.8178
    Epoch 48/100
    176/176 [==============================] - 0s 934us/step - loss: 0.3777 - accuracy: 0.8210
    Epoch 49/100
    176/176 [==============================] - 0s 947us/step - loss: 0.3778 - accuracy: 0.8203
    Epoch 50/100
    176/176 [==============================] - 0s 941us/step - loss: 0.3768 - accuracy: 0.8190
    Epoch 51/100
    176/176 [==============================] - 0s 949us/step - loss: 0.3761 - accuracy: 0.8201
    Epoch 52/100
    176/176 [==============================] - 0s 942us/step - loss: 0.3770 - accuracy: 0.8197
    Epoch 53/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3753 - accuracy: 0.8190
    Epoch 54/100
    176/176 [==============================] - 0s 896us/step - loss: 0.3749 - accuracy: 0.8240
    Epoch 55/100
    176/176 [==============================] - 0s 914us/step - loss: 0.3738 - accuracy: 0.8224
    Epoch 56/100
    176/176 [==============================] - 0s 916us/step - loss: 0.3724 - accuracy: 0.8203
    Epoch 57/100
    176/176 [==============================] - 0s 958us/step - loss: 0.3724 - accuracy: 0.8203
    Epoch 58/100
    176/176 [==============================] - 0s 920us/step - loss: 0.3713 - accuracy: 0.8219
    Epoch 59/100
    176/176 [==============================] - 0s 928us/step - loss: 0.3712 - accuracy: 0.8220
    Epoch 60/100
    176/176 [==============================] - 0s 919us/step - loss: 0.3709 - accuracy: 0.8260
    Epoch 61/100
    176/176 [==============================] - 0s 914us/step - loss: 0.3693 - accuracy: 0.8233
    Epoch 62/100
    176/176 [==============================] - 0s 918us/step - loss: 0.3693 - accuracy: 0.8238
    Epoch 63/100
    176/176 [==============================] - 0s 924us/step - loss: 0.3693 - accuracy: 0.8208
    Epoch 64/100
    176/176 [==============================] - 0s 930us/step - loss: 0.3691 - accuracy: 0.8252
    Epoch 65/100
    176/176 [==============================] - 0s 914us/step - loss: 0.3676 - accuracy: 0.8260
    Epoch 66/100
    176/176 [==============================] - 0s 943us/step - loss: 0.3664 - accuracy: 0.8254
    Epoch 67/100
    176/176 [==============================] - 0s 920us/step - loss: 0.3676 - accuracy: 0.8254
    Epoch 68/100
    176/176 [==============================] - 0s 920us/step - loss: 0.3672 - accuracy: 0.8274
    Epoch 69/100
    176/176 [==============================] - 0s 909us/step - loss: 0.3643 - accuracy: 0.8270
    Epoch 70/100
    176/176 [==============================] - 0s 919us/step - loss: 0.3651 - accuracy: 0.8272
    Epoch 71/100
    176/176 [==============================] - 0s 910us/step - loss: 0.3643 - accuracy: 0.8258
    Epoch 72/100
    176/176 [==============================] - 0s 933us/step - loss: 0.3638 - accuracy: 0.8288
    Epoch 73/100
    176/176 [==============================] - 0s 905us/step - loss: 0.3641 - accuracy: 0.8286
    Epoch 74/100
    176/176 [==============================] - 0s 912us/step - loss: 0.3623 - accuracy: 0.8270
    Epoch 75/100
    176/176 [==============================] - 0s 895us/step - loss: 0.3629 - accuracy: 0.8247
    Epoch 76/100
    176/176 [==============================] - 0s 930us/step - loss: 0.3629 - accuracy: 0.8283
    Epoch 77/100
    176/176 [==============================] - 0s 942us/step - loss: 0.3611 - accuracy: 0.8288
    Epoch 78/100
    176/176 [==============================] - 0s 986us/step - loss: 0.3615 - accuracy: 0.8263
    Epoch 79/100
    176/176 [==============================] - 0s 907us/step - loss: 0.3604 - accuracy: 0.8274
    Epoch 80/100
    176/176 [==============================] - 0s 909us/step - loss: 0.3600 - accuracy: 0.8299
    Epoch 81/100
    176/176 [==============================] - 0s 919us/step - loss: 0.3600 - accuracy: 0.8274
    Epoch 82/100
    176/176 [==============================] - 0s 918us/step - loss: 0.3598 - accuracy: 0.8295
    Epoch 83/100
    176/176 [==============================] - 0s 922us/step - loss: 0.3590 - accuracy: 0.8261
    Epoch 84/100
    176/176 [==============================] - 0s 897us/step - loss: 0.3587 - accuracy: 0.8265
    Epoch 85/100
    176/176 [==============================] - 0s 975us/step - loss: 0.3587 - accuracy: 0.8311
    Epoch 86/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3573 - accuracy: 0.8279
    Epoch 87/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3559 - accuracy: 0.8304
    Epoch 88/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3578 - accuracy: 0.8302
    Epoch 89/100
    176/176 [==============================] - 0s 908us/step - loss: 0.3563 - accuracy: 0.8311
    Epoch 90/100
    176/176 [==============================] - 0s 912us/step - loss: 0.3562 - accuracy: 0.8322
    Epoch 91/100
    176/176 [==============================] - 0s 910us/step - loss: 0.3544 - accuracy: 0.8311
    Epoch 92/100
    176/176 [==============================] - 0s 983us/step - loss: 0.3572 - accuracy: 0.8308
    Epoch 93/100
    176/176 [==============================] - 0s 917us/step - loss: 0.3544 - accuracy: 0.8318
    Epoch 94/100
    176/176 [==============================] - 0s 920us/step - loss: 0.3548 - accuracy: 0.8302
    Epoch 95/100
    176/176 [==============================] - 0s 981us/step - loss: 0.3544 - accuracy: 0.8292
    Epoch 96/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3530 - accuracy: 0.8331
    Epoch 97/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3537 - accuracy: 0.8293
    Epoch 98/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3543 - accuracy: 0.8325
    Epoch 99/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3528 - accuracy: 0.8325
    Epoch 100/100
    176/176 [==============================] - 0s 1ms/step - loss: 0.3541 - accuracy: 0.8329

Out\[40\]:

    <keras.callbacks.History at 0x7f80885d4820>

In \[41\]:

    model.evaluate(xtest,ytest)

    44/44 [==============================] - 0s 844us/step - loss: 0.4585 - accuracy: 0.7854

Out\[41\]:

    [0.4585183560848236, 0.7853589057922363]

In \[42\]:

    yp = model.predict(xtest)
    yp[:5]

    44/44 [==============================] - 0s 768us/step

Out\[42\]:

    array([[0.01295854],
           [0.11474942],
           [0.67655474],
           [0.1938232 ],
           [0.01062641]], dtype=float32)

In \[43\]:

    y_pred = []
    for element in yp:
        if element > 0.5:
            y_pred.append(1)
        else:
            y_pred.append(0)

In \[44\]:

    y_pred[:10]

Out\[44\]:

    [0, 0, 1, 0, 0, 0, 0, 0, 1, 0]

In \[46\]:

    ytest[:10]

Out\[46\]:

    2411    0
    5118    0
    5724    1
    4774    0
    1877    0
    131     1
    5631    0
    4028    0
    5588    1
    3013    0
    Name: Churn, dtype: int64

In \[48\]:

    from sklearn.metrics import confusion_matrix , classification_report

    print(classification_report(ytest,y_pred))

                  precision    recall  f1-score   support

               0       0.82      0.91      0.86      1017
               1       0.66      0.47      0.55       390

        accuracy                           0.79      1407
       macro avg       0.74      0.69      0.70      1407
    weighted avg       0.77      0.79      0.77      1407

In \[50\]:

    import seaborn as sn
    cm = tf.math.confusion_matrix(labels=ytest,predictions=y_pred)

    plt.figure(figsize = (10,7))
    sn.heatmap(cm, annot=True, fmt='d')
    plt.xlabel('Predicted')
    plt.ylabel('Truth')

Out\[50\]:

    Text(69.0, 0.5, 'Truth')

<img src="%0A" class="jp-needs-light-background" />

In \[ \]: